CREATE DATABASE Deadlocks;
GO
USE Deadlocks;
GO
CREATE TABLE element (
    id   INTEGER      NOT NULL AUTO_INCREMENT,
    data VARCHAR(128) NOT NULL,
    newData VARCHAR(128) NULL,
    PRIMARY KEY (id)
);
GO